# SMTP-Config
# smtp_server: '127.0.0.1'
# port: 25

# smtp_server: 'smtp.gmail.com'
# port: 587

# smtp_server: smtp.freesmtpservers.com
# port: 25

smtp_server: smtp.office365.com
port: 586

# Login details
username: admin123
password: admin123
